### PR TITLE
fix typo in tabs_below_navigation_toolbar_higher_navbar_positon_fx65.css

### PR DESCRIPTION
**Pull request by LighthouseKeeperYN**
I would also suggest changing it to -24px because at -28px it goes beyond the screen.

### CODE REVIEW

**Comment by Aris-t2** [comment]
Which Fx version is affected by this, Fx72+?

**Comment by LighthouseKeeperYN** [comment]
Yes.

**Comment by Aris-t2** [comment]
Then a new option is required, otherwise your change will affect Fx 65-71 too.

I will look into it.

**Comment by Aris-t2** [comment]
Sorry, you are right, its just a typo. ;-)

**Pull request merged**
