### PR TITLE
Even More AppButton Icons (DevTools)

### PR DESCRIPTION
**Pull request by B00ze64**
Added all the DevTools icons. Managed to get them by KEY so it should be multi-language (except "More Tools" which unfortunately is by label). ReUsed the DOM icon for Source and the Console icon is used for both consoles. Added quotes to your list-images (syntax highlighting friendly lol).

### CODE REVIEW

**Comment by B00ze64** [comment]
Yeah it says 2 commits because I screwed-up and created a pull request against myself lol.

**Comment by B00ze64** [comment]
Actually I found a few more icons lurking in the devtools skin, should I cancel this and redo another pull?

**Comment by B00ze64** [comment]
Ok I will try to close this and Redo with updated files.

**Comment by Acid-Crash** [comment]
@B00ze64 
Hi, There is a bug with Responsive Mode icon. It looks unnatural.

изображение

If I'm not mistaking you need to add the following to fix it.



```css
#PanelUI-developerItems toolbarbutton[key="key_responsiveDesignMode"] > image.toolbarbutton-icon {
  -moz-context-properties: fill, fill-opacity;
  fill-opacity: 0;
  list-style-image: url("chrome://devtools/skin/images/command-responsivemode.svg");
}


```
I've grabbed this based on the original icon

изображение

**Comment by B00ze64** [comment]
Wow, I had no idea, looked fine to me, who am I to tell Mozilla how to do their responsive icon lol, a big black blob is what they want then a big black blob it is! :-) Now I have to update Aris's CSS and my own CSS lol. Thanks for letting me know!

**Comment by B00ze64** [comment]
@Acid-Crash I did a new pull request to fix the icon. By the way, there are icons for those toolboxes, not SVG but PNG from an old Firefox release. If you want to propose changes to support Russian it would be cool :-)

**Pull request closed without merging**
